title: "PCB Defect Detection"
log_level: 2
inputs:
    input0:
        source: /opt/edgeai-test-data/pcb_defect_sample_images/%04d.jpg
        width: 1280
        height: 720
        framerate: 0.5
        loop: True
models:
    model0:
        model_path: /opt/model_zoo/od-8220_pcb_defect_detection_new
        viz_threshold: 0.6
outputs:
    output0:
        sink: kmssink
        width: 1920
        height: 1080

flows:
    flow0: [input0,model0,output0, [320,180,1280,720]]
